 <?php echo $this->headLink()->prependStylesheet($this->basePath('/css/build.css')); ?> 
 <?php echo $this->headLink()->prependStylesheet($this->basePath('js/plugins/multipleselect/bootstrap-multiselect.css')); ?> 
 <script src="<?php echo $this->basePath('js/plugins/multipleselect/bootstrap-multiselect.js')?>"></script>
  <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="widget style1 grey-border">
                        <div class="row">
                            <div class="col-xs-4 text-center">
                                         <i class="fa-disciples"></i>
                            </div>
                            <div class="col-xs-8 text-right">
                                <span><strong><?php echo $this->translate('DISCIPLES TREE')?> </strong></span>
                                <h2 class="font-bold">
                                <?php 
                                if(isset($stage[0]['totaluser'])){
                                    echo sprintf("%02d", $stage[0]['totaluser']);
                                }else{
                                     echo '00';
                                }
                                
                                ?>
                                
                                </h2>
                           <span><?php echo $this->translate('Total Disciples')?></span>
                            </div>
                        </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget style1 yellow-border">
                    <div class="row">
                        <div class="col-xs-4">
                          
                       <i class="fa-win"></i>
                        </div>
                        <div class="col-xs-8 text-right">
                            <span> <strong><?php echo $this->translate('WIN')?> </strong></span>
                            <h2 class="font-bold"> <?php 
                                if(isset($stage[0]['win'])){
                                    echo sprintf("%02d", $stage[0]['win']);
                                }else{
                                     echo '00';
                                }
                                
                                ?></h2>
                         <span><?php echo $this->translate('Aggressively evangelize')?> </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget style1  blue-border">
                    <div class="row">
                        <div class="col-xs-4">
                          <i class="fa-build"></i> 
                      
                        </div>
                        <div class="col-xs-8 text-right">
                            <span> <strong><?php echo $this->translate('BUILD')?> </strong></span>
                            <h2 class="font-bold"> <?php 
                                if(isset($stage[0]['build'])){
                                    echo sprintf("%02d", $stage[0]['build']);
                                }else{
                                     echo '00';
                                }
                                
                                ?></h2>
                         <span><?php echo $this->translate('Deeply build')?>  </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget style1 green-border">
                    <div class="row">
                        <div class="col-xs-4">
                            <i class="fa-send"></i>
                        </div>
                        <div class="col-xs-8 text-right">
                            <span><strong><?php echo $this->translate('SEND')?>  </strong></span>
                            <h2 class="font-bold"><?php 
                                if(isset($stage[0]['send'])){
                                    echo sprintf("%02d", $stage[0]['send']);
                                }else{
                                     echo '00';
                                }
                                
                                ?></h2>
                        <span><?php echo $this->translate('Urgently multiply')?> </span> 
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
 
 
 <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Statistics</h5>
       </div>

        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                 <label for="sel1">Select Countries </label>
                                  <select id="bulidcountries" multiple="multiple">
                             <?php  $stroption=""; $display=0; foreach($countries as $key=>$val ) { 
                                   $strselect=0;
                                  if($display<=2){  $strselect="selected='selected'";}
                               $stroption .= "<option ".$strselect. " value='".$key."' >". $val."</option>";
                                         $display++; } echo $stroption ;?>
                                </select>
                
                </div>
            </div>
            </div>
       
        <div class="row">
         
        
        
        
    <?php $display=0; foreach($countries as $key=>$val ) {  ?>
         
         
          <div id="<?php echo $key ?>"  class="col-sm-6 col-md-4  " <?php if($display>2){echo 'style="display:none;"';} $display++; ?> >
        <div class="statistics gray-bg">
            <?php 
            
              $countryName=ucwords(strtolower($val));
              ?>
            <h2><span><img src="<?php echo $this->basePath('/img/flag/'.str_replace(' ','-',$countryName).'.png')?>"></span>
        <a href="<?php echo $this->url('tree', array('action' => 'countrytree','id'=>$key))?>">  <?php echo $countryName; ?></a>
             </h2>
            <div class="row">
         <div class="col-sm-4 win"><span>Win</span><span >
         <?php 
         if(isset($buildmovements[$key]['win'])){
         echo sprintf("%02d", $buildmovements[$key]['win']);     
         }else{
             echo '00';
         }
         
         
         ?>
             
         </span></div> 
                <div class="col-sm-4 build"><span>Build</span><span >
                <?php 
             
         if(isset($buildmovements[$key]['build'])){
         echo sprintf("%02d", $buildmovements[$key]['build']);     
         }else{
             echo '00';
         }
         
         
         ?>
              
                    
                </span></div> 
                <div class="col-sm-4 send"><span>Send</span><span>
                
                
                <?php 
         if(isset($buildmovements[$key]['send'])){
         echo sprintf("%02d", $buildmovements[$key]['send']);     
         }else{
             echo '00';
         }
         
         
         ?>
                    
                    
                </span></div> 
            </div>
        </div>
    </div>
         
         
       
<?php } ?>

   
</div>
<div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Chart</h5>
       </div>
        <div class="ibox-content">
        <div class="row">
            <form class="form-inline" role="form">
 <div class="form-group col-sm-12">
  <div class="row">
        <div class="col-xs-12 col-sm-12 col-lg-6 col-md-6">
   <label for="sel1">Select Countries </label>
   <select class="form-control" id="chartcountry" multiple="multiple" >
   <?php echo $stroption ;?>
   </select>
 </div>
        <div class="col-xs-12 col-sm-12 col-lg-2 col-md-2">
 
   <label for="sel2">Select Years </label>
   <select class="form-control" id="chartcountryyear") >
   <?php for($year=2015;$year<=date('Y');$year++){ ?>
      <option <?php if($year==date('Y')){echo 'selected'; } ?>  value='<?php echo $year; ?>' ><?php echo $year; ?></option>
   <?php } ?>
   </select>
 </div>
  <div class="col-xs-12 col-sm-12 col-lg-4 col-md-4">
   
    <label for="sel3">Select Months </label>
   <select class="form-control" id="chartcountrymonth" multiple="multiple" >
    <option  value='1'>Janaury</option>
    <option value='2'>February</option>
    <option value='3'>March</option>
    <option value='4'>April</option>
    <option value='5'>May</option>
    <option value='6'>June</option>
    <option value='7'>July</option>
    <option value='8'>August</option>
    <option value='9'>September</option>
    <option value='10'>October</option>
    <option value='11'>November</option>
    <option value='12'>December</option>
   </select>
</div></div>
</div>

</form>
        </div>
        <span id="msgchart">  </span>
        <span id="buildchart"> </span>
          </div>
         
</div>
</div>
</div>


<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Alert</h4>
        </div>
        <div class="modal-body">
          <p>Please select only three countries.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
    <div class="modal-backdrop fade in inside"></div>
  </div>
   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
 <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

 <script type="text/javascript">
   function drawChart(){
          
          
          var country = $('#chartcountry option:selected');  
          var selected = [];
          $(country).each(function(index, country){
            selected.push($(this).val());
           }); 
               
          var chartcountryyear=$('#chartcountryyear option:selected').val();
          var countrymonth = $('#chartcountrymonth option:selected');  
          var selectedmonth = [];
          $(countrymonth).each(function(index, countrymonth){
           selectedmonth.push($(this).val());
           }); 
          
          alert(selected+"-- "+selectedmonth+"-- "+chartcountryyear);
          
          $.ajax({
           type: 'POST', 
           url:"<?php echo $this->url('tree', array('action'=>'ajaxchart'));?>",
           data:{ids:selected,selectedmonth:selectedmonth,chartyear:chartcountryyear},
           success:function(result)
           {
                    
             $('#buildchart').html(result);
                 
          } 
       
       }); 
    }
 
    $(document).ready(function() {
    	
    	 $('#chartcountrymonth').multiselect({      onChange: function(option, checked, select) {   drawChart();} });
    	
        $('#bulidcountries').multiselect({
           
            onChange: function(option, checked, select) {
                 var val=$(option).val();
                             
                  if (checked === true) {
                    //action taken here if true
                $('#'+val).show();
                }
                else if (checked === false) {
                $('#'+val).hide();         
                }
            
            }
        });
    
           
       $( "#chartcountryyear" ).change(function() {
        drawChart();
       });
        $('#chartcountry').multiselect({
           
            onChange: function(option, checked, select) {
            var country = $('#chartcountry option:selected');  
             var selected = [];
            if(country.length > 3) {
               
              $('#myModal').modal() ;
               $('#chartcountry').multiselect('deselect', $(option).val())
            
            
            }else{
               
                         
          drawChart();
            
            }}
        });
        
      drawChart();
    });
    
  
</script>
 <script>
     (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
             (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
     })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

     ga('create', 'UA-89408256-1', 'auto');
     ga('send', 'pageview');

 </script>