  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
  <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Schedule and to-do</h5>
       </div>
        <div class="ibox-content">
            <div class="row">
                <div class="col-sm-1 m-b-xs">
          <a href="<?php echo $this->url('schedule',
            array('action'=>'add'));?>" class="btn  btn-sm btn-secondary">Add Schedule</a>
                </div>
                <div class="col-offset-sm-8">
                 
                </div>
            </div>
               <div class="table-responsive">
                <table class="table table-striped  table-hover dataTables">
                    <thead>
                    <tr> <th class="nodisplay" ></th>
                        <th> DATE</th>
                        <th> NAME </th>
                         <th> Description </th>  
                         <th> PHONE</th>
                         <th> Action</th>
                  </tr>
                    </thead>
                    <tbody>
                    
                   
                <?php  foreach ($schedules as $schedule) : ?>
                <tr>  <td class="nodisplay" ></td>
                <td><?php echo $this->escapeHtml(date_format(date_create($schedule->time), 'g:ia \o\n l jS F Y'));?></td>
                 <td><?php echo $this->escapeHtml(ucwords($schedule->name));?></td>
                <td><?php echo $this->escapeHtml(ucwords($schedule->description));?></td>
                <td ><?php echo $this->escapeHtml(ucwords($schedule->disciple_phone));?></td>
               
                <td>
<a href="<?php echo $this->url('schedule',
            array('action'=>'edit', 'id' => $schedule->id));?>" class="tips " title="Edit">
           <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
             </a><span>&#x7C;</span><a href="<?php echo $this->url('schedule',
            array('action'=>'delete', 'id' => $schedule->id));?>" onclick="return confirm('Are you sure you want to delete this item?');" class="tips  " title="Delete"> <i class="fa fa-trash-o" aria-hidden="true"></i></a>
   	



</td>
              
            </tr>
        <?php endforeach; ?>
                 
                    </tbody>
                </table>
            </div>
            </div>
          
        </div>
        </div>
        </div>

       
        
        <?php echo $this->headScript()
 ->prependFile($this->basePath('js/plugins/dataTables/jquery.dataTables.min.js')) ;
 
  
 ?>

 <script>
        $(document).ready(function() {
            $('.dataTables').dataTable({
         "order": [[ 0, "asc" ]],
        "columnDefs": [{"targets": 4,"orderable": false} ],
            });
             
             });
 </script> 
