<link rel="stylesheet" href="/deeplife/public/css/build.css">
<script src="/deeplife/public/js/jquery-2.1.1.js"></script>
<script type="text/javascript" src="/deeplife/public/js/custom.js"></script>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Question &amp; Answere</h5>
            </div>
            <div class="ibox-content">
                <div class="question-block">
                    <div class="row">
                        <div class="col-sm-8 col-xs-12">
                            <div class="ques-category"><img src="/deeplife/public/img/send_tag.png" width="130px"> </div>
                            <div class="ques-category">
                                <span>Send </span>
                                <span>Urgently Send</span>
                            </div>
                        </div>
                        <div class="col-sm-4 col-xs-12">
                            <span class="counter">1 of 5</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="questions col-sm-12 col-xs-12">
                            <h4> <span> Q 1:</span> You see a girl waiting at the bus stop. She is exactly your type. How do you get her number She is exactly your type. How do you get her number  How do you get her number ?</h4>
                            <form role="" action="" class="ques-form">
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> Yes </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> No </label>
                                </div>
                            </form>
                            <div class="button-box">
                                <button type="button" id='next' value="Next" onlick="sum_values()" class="btn-primary btn">Next <i class="fa fa-angle-right" aria-hidden="true"></i></button>
                            </div>
                            <div class="help-box">
                                <button type="button" class="btn btn-default" data-toggle="popover" title="Help" data-content="I want help !!! aahhhhhhhh  I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh ">Help</button>
                            </div>
                        </div>
                    </div>
                   <div class="row">
                        <div class="questions thank-msg alert alert-success col-sm-12">
                            <h3> Thank You!! You have successfully finished this stage.</h3>
                            <div class="button-box">
                                <button type="button" class="btn-primary btn">Finish </button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="questions col-sm-12">
                            <h4> <span> Q 2:</span> You see a girl waiting at the bus stop. She is exactly your type. How do you get her number She is exactly your type. How do you get her number  How do you get her number ?</h4>
                            <form role="" action="" class="ques-form">
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> Yes </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> No </label>
                                </div>
                            </form>
                            <div class="button-box">
                                <button type="button" id='next' value="Next" onlick="sum_values()" class="btn-primary btn">Next <i class="fa fa-angle-right" aria-hidden="true"></i></button>
                            </div>
                            <div class="help-box">
                                <button type="button" class="btn btn-default" data-toggle="popover" title="Help" data-content="I want help !!! aahhhhhhhh  I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh ">Help</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="questions col-sm-12">
                            <h4> <span> Q 3:</span> You see a girl waiting at the bus stop. She is exactly your type. How do you get her number She is exactly your type. How do you get her number  How do you get her number ?</h4>
                            <form role="" action="" class="ques-form">
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> Yes </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> No </label>
                                </div>
                            </form>
                            <div class="button-box">
                                <button type="button" id='next' value="Next" onlick="sum_values()" class="btn-primary btn">Next <i class="fa fa-angle-right" aria-hidden="true"></i></button>
                            </div>
                            <div class="help-box">
                                <button type="button" class="btn btn-default" data-toggle="popover" title="Help" data-content="I want help !!! aahhhhhhhh  I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh ">Help</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="questions col-sm-12">
                            <h4> <span> Q 4:</span> You see a girl waiting at the bus stop. She is exactly your type. How do you get her number She is exactly your type. How do you get her number  How do you get her number ?</h4>
                            <form role="" action="" class="ques-form">
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> Yes </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> No </label>
                                </div>
                            </form>
                            <div class="button-box">
                                <button type="button" id='next' value="Next" onlick="sum_values()" class="btn-primary btn">Next <i class="fa fa-angle-right" aria-hidden="true"></i></button>
                            </div>
                            <div class="help-box">
                                <button type="button" class="btn btn-default" data-toggle="popover" title="Help" data-content="I want help !!! aahhhhhhhh  I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh ">Help</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="questions col-sm-12">
                            <h4> <span> Q 5:</span> You see a girl waiting at the bus stop. She is exactly your type. How do you get her number She is exactly your type. How do you get her number  How do you get her number ?</h4>
                            <form role="" action="" class="ques-form">
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> Yes </label>
                                </div>
                                <div class="radio radio-info radio-inline">
                                    <input type="radio" id="inlineRadio1" value="option1" name="radioInline" checked="">
                                    <label for="inlineRadio1"> No </label>
                                </div>
                            </form>
                            <div class="button-box">
                                <button type="button" id='next' value="Next" onlick="sum_values()" class="btn-primary btn">Next <i class="fa fa-angle-right" aria-hidden="true"></i></button>
                            </div>
                            <div class="help-box">
                                <button type="button" class="btn btn-default" data-toggle="popover" title="Help" data-content="I want help !!! aahhhhhhhh  I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh I want help !!! aahhhhhhhh ">Help</button>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="questions col-sm-12">
                            <h4> <span> Q 1:</span> You see a girl waiting at the bus stop. She is exactly your type. How do you get her number She is exactly your type. How do you get her number  How do you get her number ?</h4>
                            <div class="button-box">
                                <button type="button" class="btn-primary btn">Finish </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

