 <?php echo $this->headLink()->prependStylesheet($this->basePath('/css/build.css')); ?>
<?php

$title = $stage . ' Questions';
$this->headTitle($title);
?>

  <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5><?php echo $title; ?> </h5>
       </div>
          <div class="ibox-content">

                            <div class="row">
                              <div class="col-sm-12">
                                 <a href="#">
                                  <div class="share-widget style1 <?php if($stage=="WIN"){ echo 'yellow-bg'; } else { echo 'inactive';  } ?> ">
                                    <i class="fa-win"></i>
                                    Win
                                 </div>
                                 </a>
                                 <a href="#" >
                                 <div class="share-widget style1 <?php if($stage=="BUILD"){ echo 'blue-bg'; } else { echo 'inactive';  } ?> ">
                                    <i class="fa-build"></i>
                                    Build
                                 </div>
                                </a>
                                 <a href="#" >
                                 <div class="share-widget style1 <?php if($stage=="SEND"){ echo 'green-bg'; } else { echo 'inactive';  } ?>">
                                    <i class="fa-send"></i>
                                    Send
                                 </div>
                                <a>
                                </div>
                            </div>
             <form method="post" name="fshare"  action="" id="fshare">
                  <div class="form-group ">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover nowrap share-table ">
                                    <thead>
                                    <tr>
                                    <th> Sno.</th>
                                    <th> Question </th>
                                    <th> Answers </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                            <?php $snCounter=1;
                            foreach ($questions as $q) {
                                if($q['parent'] > 0 ) {
                                  ?>
                                  <tr>
                                    <td><?php  echo $snCounter++; ?></td>
                                    <td colspan="1">
                                      <a data-toggle="collapse" data-target="#ques<?php echo $q['category'];?>">
                                        <i class="fa dl-folder-icon fa-folder" aria-hidden="true"></i>&nbsp;&nbsp;
                                        <?php echo $q['foldername'];?>
                                      </a>


                                    </td>
                                    <?php
                                    $answered = 0;
                                    foreach($q['questions'] as $question) {
                                      if($question['answer'] != '') {
                                        $answered++;
                                      }
                                    }
                                    ?>
                                    <td>
                                      <h4><?php echo $answered . '/'. count($q['questions']);?></h4>
                                      <?php
                                        if($answered == count($q['questions'])) {
                                      ?>
                                          <span class="dl-complete-bar">Complete</span>
                                      <?php
                                        } else {
                                      ?>
                                          <span class="dl-progress-bar">InProgress</span>
                                      <?php
                                        }
                                      ?>

                                    </td>

                                  </tr>
                                  <tr id="ques<?php echo $q['category'];?>" class="collapse dl-folder-questions">
                                   <td colspan="3">
                                   <table class="table table-striped table-hover table-bordered">
                                <?php
                                }

                              foreach($q['questions'] as $question) {
                                ?>
                                <tr>
                                <?php
                                if($q['parent'] > 0 ) {
                                ?>
                                    <td>
                                      <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                    </td> <!-- if needed these number, otherwise remove -->
                                    <td class="dl-table-question">
                                      <a href="/movement/questiondetail/<?php echo $userid . '/' .$question['id'];?>">
                                          <?php echo $this->escapeHtml(ucwords($question['question']));?>
                                        </a>
                                    </td>
                                    <?php
                                  } else {
                                  ?>

                                      <td><?php  echo $snCounter++; ?></td>
                                      <td>
                                        <a href="/movement/questiondetail/<?php echo $userid . '/' .$question['id'];?>">
                                          <?php echo $this->escapeHtml(ucwords($question['question']));?>
                                        </a>
                                      </td>

                                  <?php
                                  } //end if($q['parent'] > 0 ) {
                                  ?>
                                      <td>
                                      <?php
                                      if($question['type'] == "YESNO") {
                                      ?>

                                          <div class="col-sm-10" style="display: inline-flex;">
                                            <div class="radio radio-info radio-inline">
                                                <input type="radio" id="inlineRadio<?php echo $question['id'] ?>" value="yes" name="answer<?php echo $question['id'] ?>" <?php if($question['answer'] == 'yes') echo 'checked="checked"';?>>
                                                <label for="inlineRadio1"> Yes </label>
                                            </div>
                                            <div class="radio radio-info radio-inline">
                                                <input type="radio" id="inlineRadio<?php echo $question['id'] ?>" value="no" name="answer<?php echo $question['id'] ?>" <?php if($question['answer'] == 'no') echo 'checked="checked"';?>>
                                                <label for="inlineRadio1"> No </label>
                                            </div>
                                          </div>

                                      <?php
                                      } else {
                                      ?>
                                      <div class="col-sm-10" style="display: inline-flex;">
                                      <span class="arrow-left addButton" attrid="<?php echo $question['id'] ?>"  ></span> <span class="increament-box">
                                          <input type="text"  oninput="this.value = this.value.replace(/[^0-9.]/g, ''); this.value = this.value.replace(/(\..*)\./g, '$1');" size="3"  name="answer<?php echo $question['id'] ?>" id="<?php echo $question['id'] ?>" value="<?php echo $question['answer']; ?>" >
                                      </span>
                                      <span class="arrow-right subButton" attrid="<?php echo $question['id'] ?>"  ></span>
                                      </div>
                                      <?php
                                      }
                                      ?>
                                      </td>


                                      </tr>

                              <?php
                              }//end inner foreach

                                if($q['parent'] > 0 ) {
                                  ?>
                                  </table>
                                  </td>
                                </tr>
                                  <?php
                                }
                              }//end main foreach
                            ?>

                        <tr>
                        <td colspan="3">
                        <input name="submit" type="submit" id="submitbutton" class="btn btn-primary pull-right" value="Save">
                        </td>
                        </tr>

                        </tbody>
                    </table>
                </div>
                </form>
                </div>

        </div>
        </div>

        </div>


 <script>

 $(document).ready(function(){

        $('.subButton').click( function() {
          var id=$(this).attr('attrid');
             var counter = $('#'+id).val();
            counter++ ;
            $('#'+id).val(counter);
    });
 $('.addButton').click( function() {
          var id=$(this).attr('attrid');
             var counter = $('#'+id).val();
         if(counter>0){
          counter-- ;
         }
            $('#'+id).val(counter);

    });




});

 </script>
