

<?php echo $this->doctype();  ?>
<html lang="en">
<?php echo $this->render('element-generic/headtitle'); ?>
<body class="." id="page-top">
<?php echo $this->render('element-generic/headnav'); ?>



<div id="inSlider" class="carousel slide carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#inSlider" data-slide-to="0" class="active"></li>
        <li data-target="#inSlider" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    <h1>We craft<br/>
                        Deeplfe System<br/>
                        beacuse WE BELIEVE<br/>
                        In Helping You</h1>
                    <p>While You doing the mission work</p>
                    <p>
                        <a class="btn btn-lg btn-primary" href="<?php echo $this->url('zfcuser/login') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>" role="button">Login</a>

                    </p>
                </div>
                <div class="carousel-image wow zoomIn">
                    <img src="img/laptopscreen.png" alt="laptop"/>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back one"></div>

        </div>
        <div class="item">
            <div class="container">
                <div class="carousel-caption blank">
                    <h1> “DON’T BE AFRAID<br/>
                        FROM NOW ON YOU WILL BE CATCHING MEN”</h1>
                    <p>Go and Make disciples</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button"><Login>login</Login></a></p>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back two"></div>
        </div>
    </div>
    <a class="left carousel-control" href="#inSlider" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#inSlider" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<section  class="container features">

    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="navy-line"></div>
            <h1>DeepLife Discipleship System <br/> <span class="navy"> Designed To Help You</span> </h1>
            <p> be come a better discipler.</p>
        </div>
    </div>
    <div class="col-md-12 text-center  wow zoomIn">
        <img src="img/appscreans2s.png" alt="dashboard" class="img-responsive">
    </div>
    <div class="row">
        <div class="col-md-3 text-center wow fadeInLeft">
            <div>
                <i class="fa fa-mobile features-icon"></i>
                <h2>Full responsive</h2>
                <p>Even though we have a native mobile both for android and iOS our web app is mobile responsive so that you have the perfect experience. </p>
            </div>
            <div class="m-t-lg">
                <i class="fa fa-bar-chart features-icon"></i>
                <h2>Reports</h2>
                <p>Have you ever wanted to know how effective you are in doing ministry? DeepLife helps you to measure your effectiveness .</p>
            </div>
        </div>
        <div class="col-md-6 text-center  wow zoomIn">
            <img src="img/appscreans1.png" alt="dashboard" class="img-responsive">
        </div>
        <div class="col-md-3 text-center wow fadeInRight">
            <div>
                <i class="fa fa-envelope features-icon"></i>
                <h2>Messaging</h2>
                <p>The messaging features helps you in communicating with your disciple.   </p>
            </div>
            <div class="m-t-lg">
                <i class="fa fa-users features-icon"></i>
                <h2>Disciple Focused</h2>
                <p>It helps you to focus in discipleship and evaluate yourself..</p>
            </div>
        </div>
    </div>

</section>

<!--<section class="container features">-->
<!--    <div class="row">-->
<!--        <div class="col-lg-12 text-center">-->
<!--            <div class="navy-line"></div>-->
<!--            <h1>Discover great features</h1>-->
<!--            <p>That features that helps you do better disciple and fulfill the great commission.. </p>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="row features-block">-->
<!--        <div class="col-lg-6 features-text wow fadeInLeft">-->
<!--            <small>INSPINIA</small>-->
<!--            <h2>Perfectly designed </h2>-->
<!--            <p>INSPINIA Admin Theme is a premium admin dashboard template with flat design concept. It is fully responsive admin dashboard template built with Bootstrap 3+ Framework, HTML5 and CSS3, Media query. It has a huge collection of reusable UI components and integrated with latest jQuery plugins.</p>-->
<!--            <a href="" class="btn btn-primary">Learn more</a>-->
<!--        </div>-->
<!--        <div class="col-lg-6 text-right wow fadeInRight">-->
<!--            <img src="img/promo3device.png" alt="dashboard" class="img-responsive pull-right">-->
<!--        </div>-->
<!--    </div>-->
<!--</section>-->

<section id="team" class="picture-section">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">

                <div class="row features-block">

                    <div class="col-lg-6 text-right wow fadeInRight">
                       <img src="img/apple.png" alt="dashboard" class="img-responsive pull-right" href="https://www.google.com.et/">
                    </div>
                    <div class="col-lg-6 wow fadeInLeft">

                        <h1 style="color: #ffffff;">Download Our Mobile App</h1>
                        <p style="color: #ffffff;">We have native applications for both android and IOS.</p>
                        <a href="https://play.google.com/store/apps/details?id=deeplife.gcme.com.deeplife&hl=en" target="_blank">
                        <div  class="col-md-6 wow fadeInUp" >
                            <img src="img/googleplay.png" class="img-responsive">
                        </div>
                            <a href="https://itunes.apple.com/us/app/deeplife/id1207542429?ls=1&mt=8" target="_blank">
                        <div class="col-md-6 wow fadeIn" >
                            <img src="img/Appstore.png" class="img-responsive big-icon">
                            <a href="#"></a>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</section>
<section class="features">
    <div class="container">
        <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="navy-line"></div>
                    <h1>Even more great features in the WebApp</h1>
                    <p>Simply breath taking </p>
                </div>
        </div>
        <div class="row features-block">
                <div class="col-lg-3 features-text wow fadeInLeft">
                    <small>Deeplife</small>
                    <h2>Breath taking features </h2>
                    <p>The Web have many features that are not yet included in the mobile app.You will be amazed with what you will find in the webapp.Specially the tree view of your disciples and how they are multiplying simply it is breath taking.  </p>
                    <a href="" class="btn btn-primary">Learn more</a>
                </div>
                <div class="col-lg-6 text-right m-t-n-lg wow zoomIn">
                    <img src="img/promo3device.png" class="img-responsive" alt="dashboard">
                </div>
                <div class="col-lg-3 features-text text-right wow fadeInRight">
                    <small>DeepLife</small>
                    <h2>Perfectly designed Native Apps </h2>
                    <p>Which use the potential of your smart phone and makes it a great tool for discipleship</p>
                    <a href="" class="btn btn-primary">Learn more</a>
                </div>
        </div>
    </div>

</section>

    <section id="testimonials" class="navy-section testimonials">

        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center wow zoomIn">
                    <i class="fa fa-comment big-icon"></i>
                    <h1>
                        Deeplife Testimonial
                    </h1>
                    <div class="testimonials-text">
                        <i>"Simply Breath Taking"</i>
                    </div>
                    <small>
                        <strong>12.02.2014 - Miheret Tilahun</strong>
                    </small>
                </div>
            </div>
        </div>

    </section>



<!---->
<!--    <section class="features">-->
<!--        <div class="container">-->
<!--        <div class="row">-->
<!--        <div class="col-lg-12 text-center">-->
<!--        <div class="navy-line"></div>-->
<!--        <h1>More and more extra great feautres</h1>-->
<!--        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. </p>-->
<!--        </div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--        <div class="col-lg-5 col-lg-offset-1 features-text">-->
<!--        <small>INSPINIA</small>-->
<!--        <h2>Perfectly designed </h2>-->
<!--        <i class="fa fa-bar-chart big-icon pull-right"></i>-->
<!--        <p>INSPINIA Admin Theme is a premium admin dashboard template with flat design concept. It is fully responsive admin dashboard template built with Bootstrap 3+ Framework, HTML5 and CSS3, Media query. It has a huge collection of reusable UI components and integrated with.</p>-->
<!--        </div>-->
<!--        <div class="col-lg-5 features-text">-->
<!--        <small>INSPINIA</small>-->
<!--        <h2>Perfectly designed </h2>-->
<!--        <i class="fa fa-bolt big-icon pull-right"></i>-->
<!--        <p>INSPINIA Admin Theme is a premium admin dashboard template with flat design concept. It is fully responsive admin dashboard template built with Bootstrap 3+ Framework, HTML5 and CSS3, Media query. It has a huge collection of reusable UI components and integrated with.</p>-->
<!--        </div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--        <div class="col-lg-5 col-lg-offset-1 features-text">-->
<!--        <small>INSPINIA</small>-->
<!--        <h2>Perfectly designed </h2>-->
<!--        <i class="fa fa-clock-o big-icon pull-right"></i>-->
<!--        <p>INSPINIA Admin Theme is a premium admin dashboard template with flat design concept. It is fully responsive admin dashboard template built with Bootstrap 3+ Framework, HTML5 and CSS3, Media query. It has a huge collection of reusable UI components and integrated with.</p>-->
<!--        </div>-->
<!--        <div class="col-lg-5 features-text">-->
<!--        <small>INSPINIA</small>-->
<!--        <h2>Perfectly designed </h2>-->
<!--        <i class="fa fa-users big-icon pull-right"></i>-->
<!--        <p>INSPINIA Admin Theme is a premium admin dashboard template with flat design concept. It is fully responsive admin dashboard template built with Bootstrap 3+ Framework, HTML5 and CSS3, Media query. It has a huge collection of reusable UI components and integrated with.</p>-->
<!--        </div>-->
<!--        </div>-->
<!--        </div>-->
<!---->
<!--    </section>-->
    <section id="pricing" class="pricing">
        <div class="container">
            <div class="row m-b-lg">
                <div class="col-lg-12 text-center">
                    <div class="navy-line"></div>
                    <h1>App Pricing</h1>
                    <p>Our App is Free and it will Always Be! </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 wow zoomIn">
                    <ul class="pricing-plan list-unstyled selected">
                        <li class="pricing-title">
                            Standard
                        </li>
                        <li class="pricing-desc">
                            Our Mission is To Help you become fruitful in your ministry.
                        </li>
                        <li class="pricing-price">
                            <span>$0</span> Free
                        </li>
                        <li>
                            Web Acces
                        </li>
                        <li>
                            Mobile App
                        </li>
                        <li>
                            Disciple Management
                        </li>
                        <li>
                            Schedule
                        </li>
                        <li>
                            Meassaging
                        </li>
                        <li>
                            Learn Environment .. And a lot more
                        </li>

                        <li>
                            <strong>Support All platform</strong>
                        </li>
                        <li>
                            <a class="btn btn-primary btn-xs" href="<?php echo $this->url('signup') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Signup</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-6 wow zoomIn">
                    <ul class="pricing-plan list-unstyled selected">
                        <li class="pricing-title">
                            Premium
                        </li>
                        <li class="pricing-desc">
                            Do you want Deeplife for your Company, Church or Mission oriented Organization
                        </li>
                        <li class="pricing-price">
                            <span>Coming Soon</span>
                        </li>
                        <li>
                            Personalised Landing Page
                        </li>
                        <li>
                            Language in your preference
                        </li>
                        <li>
                            Customisable environment
                        </li>
                        <li>
                            All features in the Standard
                        </li>
                        <li>
                            Adding your owen content
                        </li>
                        <li>
                            <strong>Support All platform</strong>
                        </li>
                        <li class="plan-action">
                            <a class="btn btn-primary btn-xs" href="#">Contact US</a>
                        </li>
                    </ul>
                </div>


            </div>
            <div class="row m-t-lg">
                <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg">
                    <p>Whether you are an individual or organization Deep Life is here to <span class="navy">Help you </span> become fruitful in the mission filed.</p>
                </div>
            </div>
        </div>

    </section>



<?php echo $this->render('element-sea/footer'); ?>
<script>!function(e,o,n){window.HSCW=o,window.HS=n,n.beacon=n.beacon||{};var t=n.beacon;t.userConfig={},t.readyQueue=[],t.config=function(e){this.userConfig=e},t.ready=function(e){this.readyQueue.push(e)},o.config={docs:{enabled:!1,baseUrl:""},contact:{enabled:!0,formId:"98e60691-c7a2-11e6-91aa-0a5fecc78a4d"}};var r=e.getElementsByTagName("script")[0],c=e.createElement("script");c.type="text/javascript",c.async=!0,c.src="https://djtflbt20bdde.cloudfront.net/",r.parentNode.insertBefore(c,r)}(document,window.HSCW||{},window.HS||{});</script>
</body>