<section id="sign-in" class="container services">
    <h1>GENERIC Landing Page</h1>
    <p>Regions:</p>
    <ul>
        <li><a href="<?php echo $this->url('sea'); ?>">Sea</a></li>
        <li><a href="<?php echo $this->url('pact'); ?>">PACT</a></li>
        <li><a href="<?php echo $this->url('ee'); ?>">Eastern Europe</a></li>
        <li><a href="<?php echo $this->url('other'); ?>">Other</a></li>
    </ul>
</section>
