<?php echo $this->doctype();?>
<html>
<head>
    <meta charset="utf-8">
     <?php echo $this->headTitle('Deeplife '. $this->translate('1.0'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('dash/css/style.css'))
        ->prependStylesheet($this->basePath('dash/css/animate.css'))
        ->prependStylesheet($this->basePath('dash/font-awesome/css/font-awesome.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))

    ; ?>

</head>
<body> 
    <div id="wrapper">
    <?php echo $this->partial('rnav'); ?>
        <div id="page-wrapper" class="gray-bg">
         <?php echo $this->partial('headnav'); ?>
         <div class="wrapper wrapper-content">
         <div class="row">
            <div class="col-lg-3">
                <div class="widget style1 white-bg">
                        <div class="row">
                            <div class="col-xs-4 text-center">
                                         <i class="fa fa-tree fa-5x"></i>
                            </div>
                            <div class="col-xs-8 text-right">
                                <span>DISCIPLES TREE </span>
                                <h2 class="font-bold"> 42</h2>
                           <span>Total Disciples</span>
                            </div>
                        </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="widget style1 navy-bg">
                    <div class="row">
                        <div class="col-xs-4">
                          
                       <i class="fa fa-shield fa-5x"></i>
                        </div>
                        <div class="col-xs-8 text-right">
                            <span> WIN </span>
                            <h2 class="font-bold">520</h2>
                         <span> Aggressively </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="widget style1  yellow-bg">
                    <div class="row">
                        <div class="col-xs-4">
                          <i class="fa fa-newspaper-o fa-5x"></i> 
                      
                        </div>
                        <div class="col-xs-8 text-right">
                            <span> BUILD </span>
                            <h2 class="font-bold">520</h2>
                         <span> New Build </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="widget style1 lazur-bg">
                    <div class="row">
                        <div class="col-xs-4">
                            <i class="fa fa-envelope-o fa-5x"></i>
                        </div>
                        <div class="col-xs-8 text-right">
                            <span> SEND </span>
                            <h2 class="font-bold">26</h2>
                        <span> Total send </span> 
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
         
      
  

       <?php echo $this->content; ?>


        </div>
  <?php echo $this->partial('footer'); ?>

      

        </div>
     
    </div>



    <!-- Mainly scripts -->
    <script src="<?php echo $this->basePath('js/jquery-2.1.1.js')?>"></script>
    <script src="<?php echo $this->basePath('js/bootstrap.min.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/metisMenu/jquery.metisMenu.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/slimscroll/jquery.slimscroll.min.js')?>"></script>

    <!-- Flot -->
    <script src="<?php echo $this->basePath('js/plugins/flot/jquery.flot.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/flot/jquery.flot.tooltip.min.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/flot/jquery.flot.spline.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/flot/jquery.flot.resize.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/flot/jquery.flot.pie.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/flot/jquery.flot.symbol.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/flot/curvedLines.js')?>"></script>

    <!-- Peity -->
    <script src="<?php echo $this->basePath('js/plugins/peity/jquery.peity.min.js')?>"></script>
    <script src="<?php echo $this->basePath('js/demo/peity-demo.js')?>"></script>

    <!-- Custom and plugin javascript -->
    <script src="<?php echo $this->basePath('js/inspinia.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/pace/pace.min.js')?>"></script>

    <!-- jQuery UI -->
    <script src="<?php echo $this->basePath('js/plugins/jquery-ui/jquery-ui.min.js')?>"></script>

    <!-- Jvectormap -->
    <script src="<?php echo $this->basePath('js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')?>"></script>
    <script src="<?php echo $this->basePath('js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')?>"></script>

    <!-- Sparkline -->
    <script src="<?php echo $this->basePath('js/plugins/sparkline/jquery.sparkline.min.js')?>"></script>

    <!-- Sparkline demo data  -->
    <script src="<?php echo $this->basePath('js/demo/sparkline-demo.js')?>"></script>


</body>
</html>
