<?php 
   if (!$this->zfcUserIdentity()) {
    
     $actual_link = "http://$_SERVER[HTTP_HOST]";
  header("Location:".$actual_link); /* Redirect browser */
    /* Make sure that code below does not get executed when we redirect. */
       exit;


                                 }

 $url=end(explode( '/',$_SERVER['REQUEST_URI']));


?>

<nav class="navbar-default navbar-static-side" role="navigation" >
        <div class="sidebar-collapse">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element"> <span>
           
                  <img alt="image" height="48" class="img-circle" src="<?php echo $this->basePath($this->zfcUserIdentity()->picture)?>" />
                                   </span>
                        <a  href="#">
                <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">
                                <?php 
                                                      
                                 
                                        echo $this->zfcUserIdentity()->displayName; ?>
                            </strong>
             </span> <span class="text-muted text-xs block">
             
             <?php 
                switch($this->zfcUserIdentity()->role_id){
                 case 2 :
                echo $admin='Super Admin Panel';
                 break;
                 case 3:
                 echo $admin='Area Admin Panel';
                 break;
                  case 4:
                 echo $admin='Country Admin Panel';
                 break;
             default :
            echo  'Missionarry'; 
             }
             ?>
             
           </span> </span> </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="" >Profile</a></li>
                             <li class="divider"></li>
                            <li><a href="<?php echo $this->url('zfcuser/logout') ?>">Logout</a></li>
                        </ul>
                    </div>
                    <div class="logo-element">
                        D+
                    </div>
                </li>
                <li <?php if($url=='dashboard'){?> class="active" <?php } ?>>
                    <a href="<?php echo $this->url('dashboard') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><i class="fa fa-th-large fa-yellow "></i> <span class="nav-label">Dashboard</span> </a>
                    </li>
                                
         <?php /* this code for  admin */ if($this->zfcUserIdentity()->role_id==2 ||$this->zfcUserIdentity()->role_id==3 ||$this->zfcUserIdentity()->role_id==4 ){
             
             switch($this->zfcUserIdentity()->role_id){
                 case 2 :
                 $admin='Super Admin Panel';
                 break;
                 case 3:
                  $admin='Area Admin Panel';
                 break;
                  case 4:
                  $admin='Country Admin Panel';
                 break;
             }
             
             
             
             
               ?>
             <li <?php if(in_array($url,array('country','movement','display','users'))){?> class="active" <?php } ?> >     <a href="#"><i class="fa fa-cog fa-yellow "></i> <span class="nav-label"><?php echo $admin; ?> </span></a>
    <ul class="nav nav-second-level">
    <li <?php if($url=='country'){?> class="subactive" <?php } ?> ><a href="<?php echo $this->url('tree', array('action'=>'country'));?>" ><i class="fa fa-tree fa-yellow"></i>Country</a></li>
    <li <?php if($url=='movement'){?> class="active" <?php } ?> ><a href="<?php echo $this->url('movement', array('action'=>'index'));?>"><i class="fa fa-question-circle fa-yellow "></i>Build Movement</a></li>
             <li <?php if($url=='display'){?> class="subactive" <?php } ?> >
        <a href="<?php echo $this->url('learn', array('action'=>'display'))  ?>">
           <i class="fa fa-leanpub fa-yellow" aria-hidden="true"></i><span class="nav-label">Learning Tools</span></a>
</li>
 <?php   if($this->zfcUserIdentity()->role_id==2 ||$this->zfcUserIdentity()->role_id==3){ ?>
                <li <?php if($url=='users'){?> class="subactive" <?php } ?> ><a href="<?php echo $this->url('users', array('action'=>'index'));?>" ><i class="fa fa-users fa-yellow "></i>
Manage Roles </a></li>
      <?php } ?>
                    </ul>
           </li>
                
                <?php } ?>      
                
                
              <li <?php if($url=='tree'){?> class="active" <?php } ?> >
        <a href="<?php echo $this->url('tree') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">
                <i class="fa fa-users fa-yellow "></i> <span class="nav-label">Generation Tree</span></a>
</li>
        
     
  <li <?php if($url=='learn'){?> class="active" <?php } ?> >
        <a href="<?php echo $this->url('learn')  ?>">
           <i class="fa fa-leanpub fa-yellow" aria-hidden="true"></i><span class="nav-label">Learn </span></a>
</li>
      <li <?php if($url=='schedule'){?> class="active" <?php } ?> >
        <a href="<?php echo $this->url('schedule') ?>">
                <i class="fa fa-clock-o  fa-yellow "></i> <span class="nav-label">Schedule</span></a>
</li>     
                
            </ul>

        </div>
    </nav>


