<nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown profile-element"> <span>
           
                  <img alt="image" class="img-circle" src="<?php echo $this->basePath("img/profile_small.jpg")?>" />
                                   </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">
                                <?php echo $this->zfcUserIdentity()->full_name; ?>
                            </strong>
                             </span> <span class="text-muted text-xs block">Missionarry <b class="caret"></b></span> </span> </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="<?php echo $this->url('dashboard/updateinfo') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Profile</a></li>
                             <li class="divider"></li>
                            <li><a href="<?php echo $this->url('zfcuser/logout') ?>">Logout</a></li>
                        </ul>
                    </div>
                    <div class="logo-element">
                        D+
                    </div>
                </li>
                <li class="active">
                    <a href="<?php echo $this->url('dashboard') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><i class="fa fa-th-large"></i> <span class="nav-label">User Dashboard</span> </a>
                    </li>
                          
            
                   <li class="">
                <a href="">
                <i class="fa fa-database"></i> <span class="nav-label">Resource</span></a>
</li>

   <li class="">
                <a href="">
                <i class="fa fa-database"></i> <span class="nav-label">News</span></a>
</li>
          
              <li>
                    <a href="#"><i class="fa fa-envelope"></i> <span class="nav-label">Mailbox </span><span class="label label-warning pull-right">16/24</span></a>
                    <ul class="nav nav-second-level">
                        <li><a href="#">Inbox</a></li>
                        <li><a href="#">Email view</a></li>
                        <li><a href="#">Compose email</a></li>
                        <li><a href="#">Email templates</a></li>
                    </ul>
                </li>
              <li class="special_link">
                <a href="<?php echo $this->url('tree') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">
                <i class="fa fa-database"></i> <span class="nav-label">Generation Tree</span></a>
</li>
            
                
            </ul>

        </div>
    </nav>


