  <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Your Disciples  </h5>
       </div>
        <div class="ibox-content">
            <div class="row">
                <div class="col-sm-9 m-b-xs">
          <a href="<?php echo $this->url('dashboard/adddisciple');?>" class="btn  btn-sm btn-primary">Add Disciple</a>
         
</p>
                </div>
                <div class="col-sm-3">
                    <div class="input-group"><input type="text" placeholder="Search" class="input-sm form-control"> <span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary"> Go!</button> </span></div>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped dataTables">
                    <thead>
                    <tr>
                         <th>Avtar</th>
                        <th>Name </th>
                        <th>Email </th>
                        <th>Phone </th>
                        <th>Country</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                      <?php  foreach ($users as $user) : ?>
            <tr> 
                <td >
                <?php
              $avatar='/avatar/noavatar.jpg';
                 if( file_exists($user->getPicture())) { 
               $avatar=$user->getPicture();
                }
                
                ?>
                
                <div style="
background-image: url('<?php echo $this->basePath($avatar);?>');
background-repeat: no-repeat;
width: 40px; 
height: 40px;
   background-size: cover; 
   background-position: center;
   border: solid 2px #fff;
" class="img-circle img-responsive"></div>	
<style>
.img-circle {
   border-radius: 50%;
}
.img-responsive {
   display: block;
   max-width: 100%;
   height: auto;
}    
tr td {
    vertical-align: middle;
}
</style>
</td>
                <td valign="middle"><?php echo $this->escapeHtml(ucwords($user->getDisplayname()));?></td>
                <td><?php echo $this->escapeHtml($user->getEmail());?></td>
                <td><?php echo $this->escapeHtml($user->getPhone());?></td>
                <td><?php echo $this->escapeHtml(ucwords($countries[$user->getCountryId()]));
                
               /// countries
                
                ?></td>
                <td>
                <a href="dashboard/edit/<?php echo $user->getId(); ?>" class="fbox tips btn btn-xs btn-primary"  >  <i class="fa fa-edit fa-fw"></i>Edit </a>
                <a href="" class="fbox tips btn btn-xs btn-danger"  >  <i class="fa fa-trash-o fa-fw"></i>Delete </a>
                  
                 </td>
            </tr>
        <?php endforeach; ?>
                   
                    </tbody>
                </table>
            </div>

        </div>
        </div>
        </div>

        </div>
