<div>
    <?php echo $this->partial('rnav'); ?>
    <?php echo $this->partial('headnav'); ?>

    <div id="page-wrapper" class="gray-bg">
        <!--top navigation-->

        <?php echo $this->partial('headtitle'); ?>
        <?php echo $this->partial('footer'); ?>
        <div class="col-lg-12" >
            <div class="row animated fadeInLeft">
                <div class="ibox float-e-margins">
                    <p></p>
                    <p>
                        <button type="button" class="btn btn-w-m btn-primary">Add Disciple</button>
                    </p>
                    <div class="ibox-content">
                        <table class="table"style="table-layout: auto">

                            <tr class="ibox-title" >
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Country</th>
                                <th>&nbsp;</th>
                            </tr>

                            <?php foreach ($users as $user) : ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($user->getDisplayname());?></td>
                                    <td><?php echo $this->escapeHtml($user->getEmail());?></td>
                                    <td><?php echo $this->escapeHtml($user->getPhoneNo());?></td>
                                    <td><?php echo $this->escapeHtml($user->getCountry());?></td>
                                    <td>
                                        <a >Edit</a>
                                        <a >Delete</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-89408256-1', 'auto');
    ga('send', 'pageview');

</script>