<div>
    <?php echo $this->partial('rnav'); ?>
    <?php echo $this->partial('headnav'); ?>

    <div id="page-wrapper" class="gray-bg">
        <!--top navigation-->

        <?php echo $this->partial('headtitle'); ?>
        <?php echo $this->partial('profile'); ?>


    </div>
    <?php echo $this->partial('footer'); ?>
</div>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-89408256-1', 'auto');
    ga('send', 'pageview');

</script>