<section id="contact" class="gray-section contact">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Contact Us</h1>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.</p>
            </div>
        </div>
        <div class="row m-b-lg">
            <div class="col-lg-3 col-lg-offset-3">
                <address>
                    <strong><span class="navy">Deeplife.</span></strong><br>
                    64 The Chase, Mount Pleasant <br>
                    S954 Harare, Zimbabwe<br>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>
            </div>
            <div class="col-lg-4">
                <p class="text-color">
                    Aggressively evangelize, deeply build, urgently multiply to launch movements and spark the fire of revival, within Southern &amp; Eastern Africa, and bring holistic transformation among unreached people groups.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
            
                <button class="btn btn-primary " data-toggle="modal" data-target="#myModalNorm">
   Contact&nbsp; <i class="fa fa-envelope-o"></i> 
</button>
<style>
    .modal-body .form-horizontal .col-sm-2,
.modal-body .form-horizontal .col-sm-10 {
    width: 100%
}

.modal-body .form-horizontal .control-label {
    text-align: left;
}
.modal-body .form-horizontal .col-sm-offset-2 {
    margin-left: 15px;
}
</style>
<!-- Modal -->
<div class="modal fade" id="myModalNorm" tabindex="-1" role="dialog" 
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" 
                   data-dismiss="modal">
                       <span aria-hidden="true">&times;</span>
                       <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                 Contact us
                </h4>
            </div>
            
            <!-- Modal Body -->
            <div class="modal-body">
                <div class="alert alert-success" style="display: none;" >
              <strong>Thank you!</strong> Your message has been successfully sent. We will contact you very soon!.
            </div>
             <div class="alert alert-danger" style="display: none;" >
         <strong>Oops!</strong> Something went wrong. Please try again later.
           </div>
                <form role="form" method="post"  >
                  
                  <div class="form-group">
                    <label for="InputName">Your Name (required)</label>
                      <input type="name" class="form-control"  name="txtname"  id="InputName" placeholder="Enter Name"/>
                  </div>
                 
                  <div class="form-group">
                    <label for="InputEmail1">Your Email (required)</label>
                      <input type="email" class="form-control" name="txtemail"  id="InputEmail1" placeholder="Enter email"/>
                  </div>
                 
                  <div class="form-group">
                    <label for="InputMessage">Your Message</label>
                      <textarea id="InputMessage" name="yourmessage" cols="40" rows="10" class="form-control" ></textarea>
                  
                  </div>
                 
                  
                <button type="button" class="btn btn-primary" id="send" >
                    SEND
                </button>
                                  
                  
                </form>
                <script>
                   $( "#send" ).click(function() { 
                    $.ajax({
         url: "<?php echo $this->serverUrl('/dashboard/contactus'); ?>",
         data: {txtname: 'test'},
         type: 'post',
         success: function(output) {
                   
                   if(output){
                       $('.alert-success').show();
                   }else{
                       $('.alert-danger').show();
                   }
                      
                  }
                }); 
                
                });
                </script>
                
            </div>
            
            <!-- Modal Footer -->
          
        </div>
    </div>
</div>
                <p class="m-t-sm">
                    Or follow us on social platform
                </p>
                <ul class="list-inline social-icon">
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
                <p><strong>© 2015 Deeplife</strong><br> 64 The Chase, Mount Pleasant, 954 Harare, Zimbabwe</p>
            </div>
        </div>
    </div>
</section>
                <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
            
        <!-- Scripts -->

 <?php echo $this->inlineScript()->prependFile($this->basePath('js/pace.min.js'))
 ->prependFile($this->basePath('js/bootstrap.min.js'))
 ->prependFile($this->basePath('js/classie.js'))
  ->prependFile($this->basePath('js/cbpAnimatedHeader.js'))
 ->prependFile($this->basePath('js/wow.min.js'))
 ->prependFile($this->basePath('js/inspinia.js')); 
 
 ?>
 
 