  <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Manage Roles </h5>
       </div>
        <div class="ibox-content">
          
                <table class="table table-striped table-bordered table-hover dataTables">
                    <thead>
                    <tr>
                         <th>AVTAR</th>
                        <th>NAME </th>
                        <th>EMAIL </th>
                        <th>PHONE </th>
                        <th>COUNTRY</th>
                         <th>ROLE</th>
                        <th>ACTION</th>
                    </tr>
                    </thead>
                    <tbody>
                      <?php  foreach ($users as $user) : ?>
            <tr> 
                <td >
                <?php
              $avatar='/avatar/noavatar.jpg';
                 if( is_file('public'.$user->picture)) { 
               $avatar=$user->picture;
                }
                
                ?>
                
                <div style="
background-image: url('<?php echo $this->basePath($avatar);?>');
background-repeat: no-repeat;
width: 40px; 
height: 40px;
   background-size: cover; 
   background-position: center;
   border: solid 2px #fff;
" class="img-circle img-responsive"></div>	
<style>
.img-circle {
   border-radius: 50%;
}
.img-responsive {
   display: block;
   max-width: 100%;
   height: auto;
}    
tr td {
    vertical-align: middle;
}
</style>


</td>
                <td valign="middle"><?php echo $this->escapeHtml(ucwords($user->displayName));?></td>
                <td><?php echo $this->escapeHtml($user->email);?></td>
                <td><?php echo $this->escapeHtml($user->phone_no);?></td>
           <td><?php echo $this->escapeHtml(ucwords(strtolower($countries[$user->country])));?></td>
            <td><?php $roleid=$user->role_id;
            switch($roleid){
                case 1:
                 echo "User";
                 break;
                case 2:
                 echo "Superadmin";
                 break;
                 case 3:
                 echo "Areaadmin";
                 break;
                 case 4:
                 echo "Countryadmin";
                 break;
               default:
                 echo "Guest";
                 break;
            }
            
            
            ?></td>
                 <td>
   <a  href="<?php echo $this->basePath('users/edit/'.$user->id);?>"  >
 <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
</a>
</td>
            </tr>
        <?php endforeach; ?>
                   
                    </tbody>
                </table>
               
            </div>
            </div>

        </div>
        </div>
      

     


   <?php echo $this->headScript()
 ->prependFile($this->basePath('js/plugins/dataTables/jquery.dataTables.js'))
 ->prependFile($this->basePath('js/plugins/dataTables/dataTables.bootstrap.js'))
 ->prependFile($this->basePath('js/plugins/dataTables/dataTables.responsive.js'))
 ->prependFile($this->basePath('js/plugins/dataTables/dataTables.tableTools.min.js')) ;
  
  echo $this->headLink()
 ->prependStylesheet($this->basePath('css/plugins/dataTables/dataTables.bootstrap.css'))
 ->prependStylesheet($this->basePath('css/plugins/dataTables/dataTables.responsive.css'))
 ->prependStylesheet($this->basePath('/css/plugins/dataTables/dataTables.tableTools.min.css')) ;
  
 ?>

 <script>
        $(document).ready(function() {
            $('.dataTables').dataTable({
        
            });
             
             });
 </script> 