<?php echo $this->headLink()->prependStylesheet($this->basePath('/css/intlTelInput.css')); ?>
<?php echo $this->headLink()->prependStylesheet($this->basePath('/css/login_reg.css')); ?>

<script src="<?php echo $this->basePath('js/intlTelInput.js')?>"></script>

<body class="white-bg" >


        <div class="middle-box text-center loginscreen animated fadeInDown">

             <img class="middle-box col-md-11" src="<?php echo $this->basePath('img/Splashlogo_xhdpi.png')?>"  href="<?php echo $this->url('home') . ($this->redirect ? '?redirect='.$this->redirect : '');?>" >

                <h2><strong style="color: #ffffff">Forgot password</strong></h2>
                <p style="color: #ffffff">Enter your email address and your password will be reset and emailed to you.</p>


                <!-- Modal Body -->

                <div class="row middle-box">
                    <br/>
                    <div class="col-lg-16">
                        <div class="alert alert-success" style="display: none;" >
                            <strong>Thank you!</strong> Your password has been successfully sent.
                        </div>
                        <div class="alert alert-danger" style="display: none;" >
                            <strong>Oops!</strong> Something went wrong. Please try again later.
                        </div>

                        <form method="get" class="form-horizontal">
                    <div class="form-group pemail">

                        <div class="col-sm-12"><input class="form-control" type="email" name="txtname" placeholder="email (required)" id="txtpemail" ></div>
                    </div>
<!--                    <div class="hr-line-dashed"></div>-->
                    <div class="form-group phone">
                        <div class="col-sm-12"><input class="form-control" name="phone" id="phone" placeholder="phone (required)" type="text">
                        </div>
                    </div>

<!--                    <div class="hr-line-dashed"></div>-->
                    <button type="button" style="align-content: center" class="btn btn-primary block btn btn-info col-md-6 full-width m-b pull-right" id="sendnewpassword" >SEND NEW PASSWORD</button>
                </form>

                        <?php echo $this->form()->closeTag() ?>
                    If you have account information kindly
                        <a style="color: #f9c123" href="<?php echo $this->url('zfcuser/login') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Login</a>
                    </div>
        </div>
        </div>

        <div class="footer" >
            <div class="pull-right">
                <strong><?php echo $this->translate('WIN'); ?></strong> <strong><?php echo $this->translate('BUILD'); ?></strong> <strong><?php echo $this->translate('SEND'); ?></strong> <?php echo $this->translate('TODAY'); ?>.
            </div>
            <div>
                <strong><?php echo $this->translate('Copyright'); ?></strong> <?php echo $this->translate('Deep Life discipleship System &copy; 2014-2015'); ?>
            </div>
        </div>

</section>

<script src="http://select2.github.io/select2/select2-3.5.3/select2.js"></script>
<script>
        $(document).ready(function() { 

            $("#country").select2();


            $('#country').change(function() {

                $('#phone_no').val($('option:selected', this).attr('data-key'));

            });
            if($('#phone_no').val() == '') {
                $('#phone_no').val($('option:selected', this).attr('data-key'));
            }

        });
    </script>
</body>

