<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Deeplife| Register</title>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
//        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
//        ->prependStylesheet($this->basePath('css/animate.min.css'))
//        ->prependStylesheet($this->basePath('css/style.min.css'))
        ->prependStylesheet($this->basePath('css/login_reg.css'))
        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
    ?>

</head>

<body class="white-bg">


<section>
    <link href="http://select2.github.io/select2/select2-3.5.3/select2.css" rel="stylesheet"/>
    <div class="container services">

        <div class="col-sm-6 col-sm-offset-3 " >
        <a href="../../">
            <div class=" wow"  >
                <img class="col-sm-10 text-center" src="<?php echo $this->basePath('img/Splashlogo_xhdpi.png')?>"
            </div>
        </a>
        </div>
        <div class="col-sm-10 ">

                    <h2 style="text-align: center;color: #FFFFFF">Sign Up</h2>
                <?php echo $this->form()->openTag($form) ?>
                <div style="text-align: center">
                    <?php foreach ($form as $element): ?>

                        <div style="color: #FFFFFF"   class="row form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
                            <label class=" col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                            <div style="color: #FFFFFF" class="col-sm-10">
                                <?php echo $this->formElement ( $element );
                                if ($this->formElementErrors ( $element ))
                                ?>
                                <span class="help-inline "><?php echo $this->formElementErrors($element) ?></span>
                            </div>
                        </div>

                    <?php endforeach ?>
                    <?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>
                    <?php echo $this->form()->closeTag() ?>
                    <a style="color: #FFFFFF">Already have an account?</a>
                    <a  href="<?php echo $this->url('zfcuser/login') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>" style="color: #f9c123">Login</a>
                </div>

        </div>

    </div>

    <script src="http://select2.github.io/select2/select2-3.5.3/select2.js"></script>
    <script>
        $(document).ready(function() {

            $("#country").select2();


            $('#country').change(function() {

                $('#phone_no').val($('option:selected', this).attr('data-key'));

            });
            if($('#phone_no').val() == '') {
                $('#phone_no').val($('option:selected', this).attr('data-key'));
            }

        });
    </script>

</section>
</body>
</html>
<div class="footer " >
    <div class="pull-right">
        <strong><?php echo $this->translate('WIN'); ?></strong> <strong><?php echo $this->translate('BUILD'); ?></strong> <strong><?php echo $this->translate('SEND'); ?></strong> <?php echo $this->translate('TODAY'); ?>.
    </div>
    <div>
        <strong><?php echo $this->translate('Copyright'); ?></strong> <?php echo $this->translate('DeepLife discipleship System &copy; 2017'); ?>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-89408256-1', 'auto');
    ga('send', 'pageview');

</script>