<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Deeplife| Register</title>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/animate.min.css'))
//        ->prependStylesheet($this->basePath('css/style.min.css'))
        ->prependStylesheet($this->basePath('css/login_reg.css'))
        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
    ?>

</head>
<body class="white-bg">
<div class="loginColumns animated fadeInUp">
    <div class="row">

        <div class="col-md-6">
            <!--            <h2 class="font-bold middle-box">Welcome to IN+</h2>-->
            <img class="middle-box col-md-12"  src="<?php echo $this->basePath('img/Splashlogo_hdpi.png')?>">
<!--            <p>-->
<!--                Perfectly designed and precisely prepared admin theme with over 50 pages with extra new web app views.-->
<!--            </p>-->

            <p class="middle-box">
                Login and get involved in the real action of helping your desciples
                by connecting to the them with in the system and monitor your progress very easily.</p> <strong>STAY BLESSED STAY CONNECTED . Get  LOGGED IN !</strong>

<!--            <p>-->
<!--                When an unknown printer took a galley of type and scrambled it to make a type specimen book.-->
<!--            </p>-->
<!---->
<!--            <p>-->
<!--                <small>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</small>-->
<!--            </p>-->

        </div>
        <div class="col-md-6">
            <div  class="- middle-box animated fadeInUp ">

                <div class=" col-sm-12 " style="vertical-align: 500px;">

                    <div style="vertical-align: 50%" class="ibox-content  text-foo  ">

                        <h2 style="color: white">Sign In</h2>
                        <h4 style="color: white">Log in with Email  or phone number </h4>
                        <?php if(strlen($flashMessages)):  ?>
                        <span class="help-inline " ><ul>    <li><?php echo $flashMessages; ?></li> </ul>
                            <?php endif; ?>
                            <?php
                            $form = $this->loginForm;
                            $form->prepare();
                            $form->setAttribute('action', $this->url('zfcuser/login'));
                            $form->setAttribute('method', 'post');
                            $form->setAttribute('class', ' ');
                            ?>
                            <?php echo $this->form()->openTag($form) ?>
                            <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
                         <?php echo $this->formElement ( $form->get('identity')->setAttribute('class', 'form-control') );
                         if ($this->formElementErrors ( $form->get('identity') ))
                         ?>
                                <span class="help-inline  error "><?php echo $this->formElementErrors($form->get('identity')) ?></span>

                        </div>
                        <div  class=" form-group">
                           <?php echo $this->formElement ( $form->get('credential')->setAttribute('class', 'form-control') );
                           if ($this->formElementErrors ( $form->get('credential') ))
                           ?>
                            <span class="help-inline  error "><?php echo $this->formElementErrors($form->get('credential')) ?></span>


                        </div>
                        <button type="submit" class="btn btn-primary block btn btn-info  full-width m-b">Login</button>

                            <?php if ($this->enableRegistration) : ?>
                                <a style="color: #f9c123" href="<?php echo $this->url('forgot') ?>">Forgot password!</a><h6 style="color: white">Not registered ? </h6>
                                <a style="color: #f9c123" href="<?php echo $this->url('signup') ?>">Sign up!</a>
                            <?php endif; ?>

                            <?php echo $this->form()->closeTag() ?>


                    </div>
                </div>
            </div>
        </div>
        <hr/>

    </div>


</body>
<div class="footer">
    <div class="pull-right" style="color: #000000">
        <strong style="color: #000000"><?php echo $this->translate('WIN'); ?></strong> <strong><?php echo $this->translate('BUILD'); ?></strong> <strong><?php echo $this->translate('SEND'); ?></strong> <?php echo $this->translate('TODAY'); ?>.
    </div>
    <div>
        <strong style="color: #000000"><?php echo $this->translate('Copyright'); ?></strong> <strong style="color: rgba(0, 0, 0, 0.58)"><?php echo $this->translate('Deep Life discipleship System &copy; 2014-2015'); ?></strong>
    </div>
</div>
</html>

<?php echo $this->inlineScript()
    ->prependFile($this->basePath('js/pace.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/classie.js'))
    ->prependFile($this->basePath('js/jquery-2.1.1.js'))
    ->prependFile($this->basePath('js/plugins/iCheck/icheck.min.js'))
    ->prependFile($this->basePath('js/cbpAnimatedHeader.js'))
    ->prependFile($this->basePath('js/wow.min.js'))
    ->prependFile($this->basePath('js/inspinia.js'));

?>
<script>
    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>
