<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Deeplife| Login</title>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/animate.min.css'))
        ->prependStylesheet($this->basePath('css/login_reg.css'))
        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
    ?>

</head>
<body class="white-bg">

<?php echo $this->headLink()->prependStylesheet($this->basePath('/css/intlTelInput.css')); ?>
<script src="<?php echo $this->basePath('js/intlTelInput.js')?>"></script>
<section id="sign-in" class="container services">
    <div></div>
    <a href="../../">
        <img class="col-sm-10 text-center" src="/img/Splashlogo_xhdpi.png" <="" div="">
    </a>
        <div class="col-sm-6">

            <div class="col-sm-12 col-sm-offset-6" >
                <h4 style="color: #FFFFFF">Log in with <span style="text-decoration: underline;cursor:pointer; color: #f9c123" id="email_span">Email</span>  or <span style="text-decoration: underline;cursor:pointer; color: #f9c123" id="phone_span" >Phone Number</span> </h4>

                <?php if(strlen($flashMessages)):  ?>
                <span class="help-inline " ><ul>    <li><?php echo $flashMessages; ?></li> </ul>
                    <?php endif; ?>

                    <?php
                    $form = $this->loginForm;
                    $form->prepare();
                    $form->setAttribute('action', $this->url('zfcuser/login'));
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('class', 'm-t');
                    ?>
                    <?php echo $this->form()->openTag($form) ?>
                    <div class="identity_div form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
                         <?php echo $this->formElement ( $form->get('identity')->setAttribute('class', 'form-control') );
                         if ($this->formElementErrors ( $form->get('identity') ))
                         ?>
                        <span class="help-inline  error "><?php echo $this->formElementErrors($form->get('identity')) ?></span>

                        </div>
                        <div class="phone_div form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
                         <?php echo $this->formElement ( $form->get('phone')->setAttribute('class', 'form-control') );
                         if ($this->formElementErrors ( $form->get('phone') ))
                         ?>
                            <span class="help-inline  error "><?php echo $this->formElementErrors($form->get('identity')) ?></span>

                        </div>
                        <div class="form-group">
                           <?php echo $this->formElement ( $form->get('credential')->setAttribute('class', 'form-control') );
                           if ($this->formElementErrors ( $form->get('credential') ))
                           ?>
                            <span class="help-inline  error "><?php echo $this->formElementErrors($form->get('credential')) ?></span>


                        </div>
                        <button type="submit" class="btn btn-primary block btn btn-info col-md-12 full-width m-b">Login</button>

                    <?php if ($this->enableRegistration) : ?>
                        <a style="color: #FFFFFF">Not registered?</a> <a href="<?php echo $this->url('signup') ?>" style="color: #f9c123">Sign up!</a>
                       <?php
                        if (stristr($_SERVER['HTTP_USER_AGENT'],'mobi')!==FALSE) {
                            ?>
                    <a style="color: #FFFFFF">Forgot password?</a> <a href="<?php echo $this->url('forgot') ?>" style="color: #f9c123"> Forgot password! </a>
                            <?php
                        } else {
                            ?>

<!--             correct it               Forgot password? <a data-toggle="modal" data-target="#myajaxforgot" >Forgot password!</a>-->
                            <a style="color: #FFFFFF">Forgot password?</a> <a href="<?php echo $this->url('forgot') ?>" style="color: #f9c123"> Forgot password! </a>
                            <?php

                        }
                        ?>
                    <?php endif; ?>

                    <?php echo $this->form()->closeTag() ?>


            </div>
        </div>
    </div>
</section>
<style>
    span.help-inline ul li {
        color: red;
        list-style: none;

    }
    .intl-tel-input {
        width: 100%;
    }
</style>
<script>
    $(document).ready(function() {
        $("#phone").intlTelInput();

        $('#phone_span').click(function() {
            $('.phone_div').show();
            $('.identity_div').hide();
            $('#identity').removeAttr('required','required');
        });

        $('#email_span').click(function() {
            $('.phone_div').hide();
            $('#identity').attr('required','required');
            $('.identity_div').show();
        });

        $('.phone_div').hide();

    });

</script>




<div class="footer">
    <div class="pull-right" style="color: #000000">
        <strong style="color: #000000"><?php echo $this->translate('WIN'); ?></strong> <strong><?php echo $this->translate('BUILD'); ?></strong> <strong><?php echo $this->translate('SEND'); ?></strong> <?php echo $this->translate('TODAY'); ?>.
    </div>
    <div>
        <strong style="color: #000000"><?php echo $this->translate('Copyright'); ?></strong> <strong style="color: rgba(0, 0, 0, 0.58)"><?php echo $this->translate('DeepLife discipleship System &copy; 2017'); ?></strong>
    </div>
</div>
</body>
</html>
<script>
    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>
